name: Release

on:
  push:
    tags:        
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go-version: [ 1.16.x ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Setup
        run: | 
          git config --global url."https://${{secrets.USER}}:${{secrets.TOKEN}}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{secrets.USER}}:${{secrets.TOKEN}}@api.github.com/".insteadOf "https://api.github.com/"

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0

      - name: Install Webpack
        run: npm install --save-dev webpack-cli

      - name: Update Addon
        if: matrix.os != 'macos-latest'
        shell: bash  
        run: ./update.sh ${{secrets.USER}} ${{secrets.TOKEN}} ${{matrix.os}}

      - name: Update Addon
        if: matrix.os == 'macos-latest'
        shell: bash  
        run: |
          ./update.sh ${{secrets.USER}} ${{secrets.TOKEN}} ${{matrix.os}} arm
          ./update.sh ${{secrets.USER}} ${{secrets.TOKEN}} ${{matrix.os}} amd

      - name: Update Deps
        run: npm run build:deps

      - name: Build Front
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{secrets.TOKEN}}
          mac_certs: ${{ secrets.MAC_CERT_TEXT }}
          mac_certs_password: ${{ secrets.MAC_CERT_PASS }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          DEBUG: electron-builder
          APPLEID: ${{ secrets.APPLEID }}
          APPLEIDPASS: ${{ secrets.APPLEIDPASS }}
          DO_KEY_ID: ${{ secrets.DO_KEY_ID }}
          DO_SECRET_KEY: ${{ secrets.DO_SECRET_KEY }}

      - name: Make artifacts dir
        run: | 
          mkdir -p artifacts

      - name: Cleanup artifacts
        if: matrix.os != 'windows-latest'
        run: |
          mv dist/*.{zip,dmg,deb,AppImage,exe} artifacts || true

      - name: Cleanup artifacts Win
        if: matrix.os == 'windows-latest'
        run: |
          mv dist/*.exe artifacts

      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}

      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 3
          delete_tag_pattern: alpha
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
