name: Release
on: 
  push:
    tags:        
      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12.10.0

      - name: Build
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

      - name: Make artifacts dir
        run: | 
          mkdir -p artifacts

      - name: Cleanup artifacts
        if: matrix.os != 'windows-latest'
        run: |
          mv dist/*.{zip,dmg,deb,AppImage,exe} artifacts || true

      - name: Cleanup artifacts Win
        if: matrix.os == 'windows-latest'
        run: |
          mv dist/*.exe artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.os}}
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
