name: Release
on: push

#on: 
#  push:
#    tags:        
#      - v*

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go-version: [ 1.13.x ]
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - name: Setup
        run: | 
          git config --global url."https://${{secrets.USER}}:${{secrets.TOKEN}}@github.com/".insteadOf "https://github.com/"
          git config --global url."https://${{secrets.USER}}:${{secrets.TOKEN}}@api.github.com/".insteadOf "https://api.github.com/"

      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 12.10.0

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}

      - name: Set GOPATH
		if: matrix.os != 'windows-latest'
        run: export GOPATH=~/go

      - name: Checkout Middleware
        uses: actions/checkout@v2
        with:
          repository: 'anytypeio/go-anytype-middleware'
          token: ${{secrets.TOKEN}}
          path: go-anytype-middleware

      - name: Install Protoc
        uses: Arduino/actions/setup-protoc@master

      - name: Build Middleware
        run: | 
          export GOPATH=~/go
          cd go-anytype-middleware
          go mod download
          make setup-protoc
          make protos
          make build-lib
          make build-js

      - name: Build Front
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{secrets.TOKEN}}

      - name: Make artifacts dir
        run: | 
          mkdir -p artifacts

      - name: Cleanup artifacts
        if: matrix.os != 'windows-latest'
        run: |
          mv dist/*.{zip,dmg,deb,AppImage,exe} artifacts || true

      - name: Cleanup artifacts Win
        if: matrix.os == 'windows-latest'
        run: |
          mv dist/*.exe artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{matrix.os}}
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "artifacts/**"
        env:
          GITHUB_TOKEN: ${{secrets.TOKEN}}
